---
- name: config | component | kubelet args | check bkp
  become: true
  stat:
    path: /var/snap/microk8s/current/args/kubelet.orig
  register: kubelet_orig_file

- name: config | component | kubelet args | create bkp
  become: true
  ansible.builtin.copy:
    src: /var/snap/microk8s/current/args/kubelet
    dest: /var/snap/microk8s/current/args/kubelet.orig
    remote_src: yes
  when: not kubelet_orig_file.stat.exists
  notify: restart kubelite

- name: config | component | kubelet args | restore orig config
  become: true
  ansible.builtin.copy:
    src: /var/snap/microk8s/current/args/kubelet.orig
    dest: /var/snap/microk8s/current/args/kubelet
    remote_src: yes
  when: kubelet_orig_file.stat.exists
  notify: restart kubelite

- name: config | component | kubelet args | append args
  become: true
  loop: "{{ microk8s_kubelet_additional_args }}"
  lineinfile:
    path: /var/snap/microk8s/current/args/kubelet
    line: "{{ item }}"
    state: present
  notify: restart kubelite
